[project]
name = "backend-demo-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.45",
    "fastapi>=0.118.0",
    "motor>=3.7.1",
    "python-multipart>=0.0.20",
    "uvicorn>=0.37.0",
]
